---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu/trusty64

suites:
  - name: default
    run_list:
      - recipe[issue-elastic::issue-elasticsearch]
      #- recipe[issue-elastic::issue-elasticsearch-monitoring]
      #- recipe[issue-elastic::issue-elasticsearch-gate]
    attributes:
      issue:
        aws_access_key: 1234
        aws_secret_key: 1234
        elasticsearch_monitoring_cluster: "https://bam:bam@es-mon:9200"
